# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hv2pACVsSHHz4vl00ghrLSfrLMnaRjXM
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")

df.head()

df.shape

df.columns

df.info()

df.info()

df.isnull().sum()

df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

df.drop_duplicates(inplace=True)

df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df['stroke'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6)
)

plt.title("Stroke Distribution")
plt.ylabel("")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['age'], bins=30, kde=True)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.show()

age_glucose = df.groupby('age')['avg_glucose_level'].mean()

plt.figure(figsize=(10,5))

plt.plot(age_glucose.index, age_glucose.values)

plt.title("Average Glucose Level by Age")
plt.xlabel("Age")
plt.ylabel("Glucose")
plt.show()

sns.countplot(x='gender', hue='stroke', data=df)

plt.title("Stroke by Gender")
plt.show()

sns.scatterplot(
    x='bmi',
    y='avg_glucose_level',
    hue='stroke',
    data=df
)

plt.title("BMI vs Glucose")
plt.show()

sns.boxplot(x='stroke', y='age', data=df)

plt.title("Age Distribution by Stroke")
plt.show()

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(10,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

age_counts = df['age'].value_counts().sort_index()

age_counts.plot.area(figsize=(10,5))

plt.title("Age Area Chart")
plt.show()

sns.countplot(x='smoking_status', data=df)

plt.xticks(rotation=45)

plt.title("Smoking Status Count")
plt.show()

sns.violinplot(x='stroke', y='bmi', data=df)

plt.title("BMI Distribution by Stroke")
plt.show()

"""# Dataset Overview

The Stroke Prediction Dataset contains healthcare-related information of patients and is used to analyze factors associated with stroke occurrence. The dataset includes demographic, medical, and lifestyle-related features such as age, gender, hypertension, heart disease, BMI, glucose level, smoking status, marital status, and work type. The target variable is stroke, where 0 represents no stroke and 1 represents stroke occurrence.

# Data Cleaning Summary

The dataset was checked for missing values, duplicate records, and incorrect data types. Missing values in the BMI column were replaced using the mean BMI value. Duplicate rows were removed to improve data quality. Numerical and categorical features were verified before performing analysis and visualization.

# Age Analysis

## Observation

Most patients belong to middle-aged and older age groups. Stroke cases are significantly higher among elderly individuals compared to younger people.

## Conclusion

Age is one of the strongest factors influencing stroke occurrence.

# Gender Analysis

## Observation

The dataset contains both male and female patients in nearly balanced proportions. Stroke cases appear slightly higher among older female patients.

## Conclusion

Gender alone does not strongly determine stroke occurrence, but it may have slight influence in older age groups.

# Hypertension Analysis

## Observation

Patients with hypertension show noticeably higher stroke frequency compared to patients without hypertension.

## Conclusion

Hypertension is strongly associated with increased stroke risk.

# Heart Disease Analysis

## Observation

Patients suffering from heart disease have a higher probability of stroke occurrence compared to healthy individuals.

## Conclusion

Heart disease is an important medical factor contributing to stroke.

# BMI Analysis

## Observation

The BMI distribution contains several outliers. Many stroke patients fall into overweight or obese BMI ranges.

## Conclusion

Higher BMI may increase stroke susceptibility when combined with other health conditions.

# Glucose Level Analysis

## Observation

Stroke patients tend to have higher average glucose levels compared to non-stroke patients.

## Conclusion

High glucose level is one of the strongest indicators of stroke occurrence.

# Smoking Status Analysis

## Observation

Former smokers and current smokers show relatively higher stroke frequency than never-smokers.

## Conclusion

Smoking behavior contributes to increased stroke risk.

# Marital Status Analysis

## Observation

Married individuals show higher stroke frequency, mainly because older age groups dominate married populations.

## Conclusion

Marital status itself may not directly affect stroke risk but may correlate with age-related factors.

# Work Type Analysis

## Observation

Private-sector workers form the majority of the dataset. Self-employed individuals and older adults show relatively higher stroke occurrence.

## Conclusion

Occupation type may indirectly influence stress levels and health conditions.

# Correlation Analysis

The correlation heatmap indicates that age, hypertension, heart disease, and glucose level have positive relationships with stroke occurrence. BMI shows weaker correlation compared to other medical features.

# Pie Chart Insight

## Stroke Distribution

The dataset contains a much larger number of non-stroke cases compared to stroke cases, indicating class imbalance.

# Histogram Insight

## Age Distribution

Most individuals in the dataset fall between 30 and 60 years of age.

# Line Chart Insight

## Glucose Trends by Age

Average glucose levels generally increase with age.

# Bar Chart Insight

## Stroke by Gender

Stroke cases are distributed across both genders with slightly higher cases among females.

# Scatter Plot Insight

## BMI vs Glucose

Higher BMI and glucose combinations are more common among stroke-positive patients.

# Box Plot Insight

## Age Spread

Stroke patients have a much higher median age than non-stroke patients.

# Heatmap Insight

## Feature Relationships

Stroke has stronger relationships with age, hypertension, heart disease, and glucose level.

# Violin Plot Insight

## BMI Density

Stroke-positive patients show denser BMI distribution in overweight ranges.

# Major Findings

## Finding 1

Older individuals are significantly more vulnerable to stroke.

## Finding 2

Hypertension strongly increases stroke probability.

## Finding 3

Patients with heart disease have higher stroke risk.

## Finding 4

High glucose levels are associated with stroke occurrence.

## Finding 5

Smoking contributes to increased stroke frequency.

## Finding 6

The dataset is imbalanced because stroke cases are limited.

## Finding 7

BMI contributes to stroke risk when combined with other conditions.

## Finding 8

Multiple medical conditions together increase stroke probability.

## Finding 9

Lifestyle and medical factors jointly influence stroke occurrence.

## Finding 10

Preventive healthcare and early diagnosis are important for reducing stroke risk.

# Recommendations

## Recommendation 1

Patients should regularly monitor blood glucose levels.

## Recommendation 2

Hypertension patients should undergo routine stroke screening.

## Recommendation 3

Smoking reduction campaigns should be promoted for public awareness.

## Recommendation 4

Older individuals should receive frequent health checkups.

## Recommendation 5

Healthy diet and exercise should be encouraged to maintain proper BMI.

## Recommendation 6

Healthcare systems should focus on early detection of cardiovascular diseases.

## Recommendation 7

Lifestyle improvements can significantly reduce stroke-related risks.

## Recommendation 8

Patients with multiple health conditions require continuous medical supervision.

# Final Conclusion

This exploratory data analysis identified several important factors associated with stroke occurrence. Age, hypertension, heart disease, glucose level, and smoking status were found to be major contributors to stroke risk. The dashboard provides interactive visualizations and filtering options to help users analyze healthcare data efficiently. This project demonstrates practical application of data preprocessing, visualization, exploratory analysis, and dashboard development using Python libraries and Streamlit.

# Future Improvements

Future versions of this project may include machine learning-based stroke prediction, advanced statistical analysis, real-time healthcare monitoring, and AI-powered healthcare recommendations.

"""